modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/seasonhud"
logoFile = "${mod_id}.png"
authors = "${mod_author}" #optional
description = "${description}"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${ mod_id }]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "sereneseasons"
mandatory = true
versionRange = "[8.1.0.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "xaerominimap"
mandatory = false
versionRange = "[24.0.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "ftbchunks"
mandatory = false
versionRange = "[1902.3.22-build.271,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "map_atlases"
mandatory = false
versionRange = "[1.19-6.0.0,)"
ordering = "AFTER"
side = "CLIENT"