modLoader = "javafml" #mandatory
loaderVersion = "[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "seasonhud" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "SeasonHUD" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/seasonhud"
logoFile= "SeasonHud.png"
logoBlur = true
authors="IanAnderson" #optional
description ='''
This is an addon for SereneSeasons that displays the current season on the HUD or under a minimap'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.seasonhud]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[45,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency

[[dependencies.seasonhud]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seasonhud]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.19.3-8.3.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.seasonhud]]
modId = "xaerominimap"
mandatory = false
versionRange = "[23.3.3,)"
ordering = "AFTER"
side = "CLIENT"